package generator

import "text/template"

var fileTpl = template.Must(template.New("file").Parse(fileTemplate))

const fileTemplate = `// Code generated by protoc-gen-go-mcp. DO NOT EDIT.
// source: {{ .SourcePath }}

package {{ .GoPackage }}mcp

import (
	"context"
	"encoding/json"

	mcpcore "github.com/panyam/mcpkit/core"
	"github.com/panyam/mcpkit/ext/protogen/runtime"
	"github.com/panyam/mcpkit/server"
	"google.golang.org/protobuf/encoding/protojson"
	grpc "google.golang.org/grpc"
	"connectrpc.com/connect"
)

// Ensure imports are used.
var (
	_ context.Context
	_ json.RawMessage
	_ mcpcore.ToolDef
	_ runtime.RPCError  // unused import guard for runtime; TODO: remove once used
	_ protojson.MarshalOptions
	_ grpc.ClientConnInterface
	_ connect.Request[struct{}]
)

{{ range .Services }}
// --- {{ .Name }} ---

{{ template "serverInterface" . }}
{{ template "registerInProcess" . }}
{{ template "grpcClientInterface" . }}
{{ template "forwardToGRPC" . }}
{{ template "connectClientInterface" . }}
{{ template "forwardToConnect" . }}
{{ end }}

{{- define "serverInterface" -}}
// {{ .Name }}MCPServer is the interface that in-process implementations must satisfy.
type {{ .Name }}MCPServer interface {
{{- range .Tools }}
	{{ .MethodName }}(ctx context.Context, req *{{ .RequestType }}) (*{{ .ResponseType }}, error)
{{- end }}
}
{{ end }}

{{- define "registerInProcess" -}}
// Register{{ .Name }}MCP registers MCP tools from {{ .Name }} with an in-process implementation.
func Register{{ .Name }}MCP(srv *server.Server, impl {{ .Name }}MCPServer) {
	srv.Register(
{{- range .Tools }}
		{{ template "toolDef" . }}{
			Handler: func(ctx context.Context, req mcpcore.ToolRequest) (mcpcore.ToolResult, error) {
				var in {{ .RequestType }}
				if err := runtime.BindProto(req, &in); err != nil {
					return mcpcore.ErrorResult(err.Error()), nil
				}
				resp, err := impl.{{ .MethodName }}(ctx, &in)
				if err != nil {
					return runtime.RPCError(err)
				}
				{{ if .Structured -}}
				return runtime.ProtoStructuredResult(resp)
				{{- else -}}
				return runtime.ProtoTextResult(resp)
				{{- end }}
			},
		},
{{- end }}
	)
}
{{ end }}

{{- define "grpcClientInterface" -}}
// {{ .Name }}GRPCClient is the gRPC client interface for forwarding.
type {{ .Name }}GRPCClient interface {
{{- range .Tools }}
	{{ .MethodName }}(ctx context.Context, req *{{ .RequestType }}, opts ...grpc.CallOption) (*{{ .ResponseType }}, error)
{{- end }}
}
{{ end }}

{{- define "forwardToGRPC" -}}
// Forward{{ .Name }}ToGRPC registers MCP tools that forward to a gRPC {{ .Name }} client.
func Forward{{ .Name }}ToGRPC(srv *server.Server, client {{ .Name }}GRPCClient) {
	srv.Register(
{{- range .Tools }}
		{{ template "toolDef" . }}{
			Handler: func(ctx context.Context, req mcpcore.ToolRequest) (mcpcore.ToolResult, error) {
				var in {{ .RequestType }}
				if err := runtime.BindProto(req, &in); err != nil {
					return mcpcore.ErrorResult(err.Error()), nil
				}
				resp, err := client.{{ .MethodName }}(ctx, &in)
				if err != nil {
					return runtime.RPCError(err)
				}
				{{ if .Structured -}}
				return runtime.ProtoStructuredResult(resp)
				{{- else -}}
				return runtime.ProtoTextResult(resp)
				{{- end }}
			},
		},
{{- end }}
	)
}
{{ end }}

{{- define "connectClientInterface" -}}
// Connect{{ .Name }}Client is the ConnectRPC client interface for forwarding.
type Connect{{ .Name }}Client interface {
{{- range .Tools }}
	{{ .MethodName }}(ctx context.Context, req *connect.Request[{{ .RequestType }}]) (*connect.Response[{{ .ResponseType }}], error)
{{- end }}
}
{{ end }}

{{- define "forwardToConnect" -}}
// Forward{{ .Name }}ToConnect registers MCP tools that forward to a ConnectRPC {{ .Name }} client.
func Forward{{ .Name }}ToConnect(srv *server.Server, client Connect{{ .Name }}Client) {
	srv.Register(
{{- range .Tools }}
		{{ template "toolDef" . }}{
			Handler: func(ctx context.Context, req mcpcore.ToolRequest) (mcpcore.ToolResult, error) {
				var in {{ .RequestType }}
				if err := runtime.BindProto(req, &in); err != nil {
					return mcpcore.ErrorResult(err.Error()), nil
				}
				resp, err := client.{{ .MethodName }}(ctx, connect.NewRequest(&in))
				if err != nil {
					return runtime.RPCError(err)
				}
				{{ if .Structured -}}
				return runtime.ProtoStructuredResult(resp.Msg)
				{{- else -}}
				return runtime.ProtoTextResult(resp.Msg)
				{{- end }}
			},
		},
{{- end }}
	)
}
{{ end }}

{{- define "toolDef" -}}
server.Tool{
			ToolDef: mcpcore.ToolDef{
				Name:        "{{ .ToolName }}",
				Description: "{{ .Description }}",
				InputSchema: json.RawMessage(` + "`" + `{{ .InputSchema }}` + "`" + `),
			},
{{- end }}
`
