// origin.go — self-receive transport plumbing for Pattern B wirings
// (publisher + subscriber colocated on the same replica).
//
// The Pattern B problem: any cross-process pub/sub transport (Redis
// PUBLISH/SUBSCRIBE, Kafka, NATS, etc.) used to relay events across
// replicas also delivers a replica's own publishes back to its own
// subscriber. If the subscriber blindly runs the local fanout on
// receive, every event yielded on a replica fires its local stream
// targets / webhook deliveries TWICE — once via yield's in-process
// for-loop, once via the round-trip through the transport.
//
// The fix: each Publisher carries a per-process origin marker; it
// stamps that marker onto event.Meta[OriginMetaKey] at publish time;
// the colocated Subscriber knows the marker and drops messages that
// carry it. Cross-replica subscribers see no marker (or a different
// one) and process the event normally.
//
// This file defines the seam — the meta key + accessor helpers — so
// every Emitter/Subscriber pair following Pattern B uses the same
// plumbing. Per-instance origin IDs themselves are generated by the
// concrete Publisher's constructor (each implementation knows how
// long-lived its connections are; a UUID/random hex generated at
// startup is the common case).
package events

// OriginMetaKey is the Event.Meta key under which Pattern B publishers
// stamp their per-instance origin marker. Subscribers that observe a
// matching value on incoming events drop them — they originated on
// this replica and were already locally delivered before the publish.
//
// Underscore prefix follows the "internal/private" convention so this
// can't collide with any spec-defined `_meta` field; the
// events-namespaced suffix lets a future second transport layer (e.g.
// MCP wire → Kafka relay) leave its own marker distinct from this one.
//
// The key is always stripped from event.Meta before the Subscriber
// hands the event to its deliverFn — consumers never see it.
const OriginMetaKey = "_mcpkit_events_origin"

// OriginIDFromMeta returns the origin marker carried on event.Meta, or
// "" if absent / wrong-typed. Subscribers compare the returned value to
// their configured "skip" origin to decide whether to drop the message.
func OriginIDFromMeta(meta map[string]any) string {
	if meta == nil {
		return ""
	}
	v, _ := meta[OriginMetaKey].(string)
	return v
}

// StripOriginIDFromMeta removes the origin marker from event.Meta so
// downstream consumers (delivery handlers, webhook receivers, stream
// subscribers) never see it. Returns the same map for chaining; nil-in,
// nil-out. Idempotent.
func StripOriginIDFromMeta(meta map[string]any) map[string]any {
	if meta == nil {
		return nil
	}
	delete(meta, OriginMetaKey)
	return meta
}

// StampOriginIDOnMeta returns a Meta map carrying originID under
// OriginMetaKey. Always returns a freshly-allocated map so callers
// passing the event's Meta in don't see their map mutated through
// aliasing — Event is passed by value but Meta is a reference type.
// An empty originID is a no-op: returns the input unchanged.
func StampOriginIDOnMeta(meta map[string]any, originID string) map[string]any {
	if originID == "" {
		return meta
	}
	cp := make(map[string]any, len(meta)+1)
	for k, v := range meta {
		cp[k] = v
	}
	cp[OriginMetaKey] = originID
	return cp
}
