package main

import (
	"encoding/json"
	"fmt"

	"github.com/panyam/demokit"
	"github.com/panyam/mcpkit/client"
	"github.com/panyam/mcpkit/core"
	"github.com/panyam/mcpkit/examples/common"
)

// runDemo is the cohort-heatmap walkthrough. Acts as a scripted MCP
// host against a server started by `just serve` in another terminal.
//
// Walks four wire-level steps + a closing narrative Section. The
// fixture's pedagogical anchors are:
//
//   - Enum + default inputs (`metric`, `periodType`) reflected cleanly
//     from struct tags — no InputSchemaPatch needed.
//   - Idiomatic Go integer types throughout (cohortIndex, periodIndex,
//     usersRetained, usersOriginal). Upstream's zod schemas use
//     `z.number()` (TypeScript's number is a 64-bit float, can't
//     distinguish int from float); the apps/compat parity diff
//     normalizes `"integer"` ↔ `"number"` so the divergence doesn't
//     fire as drift.
//   - 12×12 dataset generated by a seeded PCG-driven exponential-decay
//     curve. The seed makes the snapshot baseline stable; the per-cell
//     retention math is byte-for-byte the same as upstream's
//     `generateCohortData()` in server.ts.
//   - Iframe-side bridge dance is moderate: `app.callServerTool` per
//     filter change, plus `app.getHostContext` for host theming.
//     Notably NO `app.registerTool` and NO `app.updateModelContext` —
//     this fixture sits between quickstart (bare-minimum bridge dance)
//     and budget-allocator (rich bridge dance) on the App-ness spectrum.
//
//  1. Connect (initialize + notifications/initialized).
//  2. tools/list — focus on `inputSchema.properties.{metric,periodType}`
//     to surface the enum + default story, and `_meta.ui.resourceUri`
//     as the signal that this tool drives an iframe.
//  3. tools/call get-cohort-data {} — let the schema defaults kick in
//     server-side. Summarize the structuredContent shape (12 cohorts ×
//     12 periods × 12 cells/cohort) without dumping ~1000 numbers; also
//     surface the human-readable text in content[0].text.
//  4. resources/read on ui://get-cohort-data/mcp-app.html — pull the
//     iframe HTML bytes plus inspect the per-content `_meta`.
//  5. (Section) "What the App iframe does with all this" — narrates
//     the bridge dance: useApp hook connects to the host, dropdown
//     state in React triggers app.callServerTool with new arguments,
//     structuredContent is unpacked into the heatmap. Compares to
//     quickstart and budget-allocator so a reader can see where
//     cohort-heatmap sits on the App-ness spectrum.
//
// Each tool/resource step attaches two unboxed Verbatim blocks via
// common.WireRecipe: a curl form (copy-pastable) and a Go form (the
// equivalent *client.Client call).
func runDemo() {
	serverURL := common.MCPServerURL()

	demo := demokit.New("cohort-heatmap — 12×12 retention dataset with enum/default schema").
		Dir("cohort-heatmap").
		Description("Walks the get-cohort-data round trip end-to-end as a scripted MCP client. Two distinctive things visible on the wire: the enum + default input schema (metric/periodType) reflected cleanly from struct tags, and the deeply nested structuredContent payload (12 cohorts × 12 periods × 5 numeric fields per cell) generated by a seeded exponential-decay curve so the visual baseline stays stable. The final narrative section spells out the moderate bridge dance: app.callServerTool on filter changes, app.getHostContext for theming, no app.registerTool, no app.updateModelContext. Run `just serve` in another terminal first.").
		Actors(
			demokit.Actor("Host", "MCP Host (this client)"),
			demokit.Actor("Server", "mcpkit-Go fixture (just serve)"),
		)

	demo.Section("Setup",
		"Start the MCP server in a separate terminal first:",
		"",
		"```",
		"Terminal 1:  just serve         # mcpkit-Go fixture on :3101 by default",
		"Terminal 2:  just demo          # this walkthrough (--tui for interactive TUI)",
		"```",
		"",
		"Point the walkthrough at a different host via either of:",
		"",
		"```",
		"go run . --demo --url http://localhost:1234       # CLI flag",
		"MCPKIT_SERVER_URL=http://localhost:1234 just demo # env var",
		"```",
		"",
		"Any MCP host can connect to the running server (Claude Desktop, VS Code, MCPJam, basic-host). The walkthrough below acts as a scripted host that issues the protocol calls directly through `*mcpkit/client.Client` — no LLM, no browser, no JS. The same protocol calls drive the iframe when you run `just demo-app EXAMPLE=cohort-heatmap` in basic-host (see the [centralized guide](../README.md#other-ways-to-test-a-fixture)).",
	)

	var c *client.Client

	step1 := demo.Step("Connect to the fixture").
		Arrow("Host", "Server", "POST /mcp — initialize").
		DashedArrow("Server", "Host", "serverInfo + capabilities + Mcp-Session-Id").
		Note("Session establishment is a single initialize round-trip plus the notifications/initialized ack. `*client.Client.Connect()` does both behind one call; the curl form below shows the raw shape.")
	common.WireRecipe(step1,
		`# Initialize. Mcp-Session-Id comes back in the response headers.
SID=$(curl -si -X POST `+serverURL+`/mcp \
  -H 'Content-Type: application/json' \
  -H 'Accept: text/event-stream, application/json' \
  -d '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-11-25","capabilities":{},"clientInfo":{"name":"curl","version":"1"}}}' \
  | awk 'tolower($1) == "mcp-session-id:" {gsub(/\r/,""); print $2}')

# Acknowledge so the server's dispatcher unblocks.
curl -s -X POST `+serverURL+`/mcp \
  -H "Mcp-Session-Id: $SID" \
  -H 'Content-Type: application/json' \
  -H 'Accept: text/event-stream, application/json' \
  -d '{"jsonrpc":"2.0","method":"notifications/initialized"}'`,
		`c := client.NewClient("`+serverURL+`/mcp",
    core.ClientInfo{Name: "cohort-heatmap-host", Version: "1.0"},
)
if err := c.Connect(); err != nil {
    log.Fatalf("connect: %v", err)
}
// Connect() handles initialize + notifications/initialized + session header.
fmt.Printf("connected to %s %s\n", c.ServerInfo.Name, c.ServerInfo.Version)`,
	).Run(func(ctx demokit.StepContext) *demokit.StepResult {
		c = client.NewClient(serverURL+"/mcp",
			core.ClientInfo{Name: "cohort-heatmap-host", Version: "1.0"},
		)
		if err := c.Connect(); err != nil {
			fmt.Printf("    ERROR: %v\n    Start the server with: just serve\n", err)
			return nil
		}
		fmt.Printf("    connected to %s %s\n", c.ServerInfo.Name, c.ServerInfo.Version)
		return nil
	})

	step2 := demo.Step("tools/list — verify get-cohort-data + its enum/default input schema").
		Arrow("Host", "Server", "tools/list").
		DashedArrow("Server", "Host", "tools[] including get-cohort-data").
		Note("Two interesting bits in the response. (1) `_meta.ui.resourceUri` tells an MCP Apps host \"render this tool's result inside the iframe at that ui:// URI.\" (2) `inputSchema.properties.metric` / `inputSchema.properties.periodType` carry enums + defaults reflected cleanly from struct tags — no InputSchemaPatch needed. The walkthrough prints just the metric + periodType property shapes below to highlight the enum-with-default convention.")
	common.WireRecipe(step2,
		`curl -s -X POST `+serverURL+`/mcp \
  -H "Mcp-Session-Id: $SID" \
  -H 'Content-Type: application/json' \
  -H 'Accept: text/event-stream, application/json' \
  -d '{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}' \
  | jq '.result.tools[] | {name, _meta, metric: .inputSchema.properties.metric, periodType: .inputSchema.properties.periodType}'`,
		`res, _ := c.Call("tools/list", map[string]any{})
var out struct {
    Tools []struct {
        Name        string         `+"`json:\"name\"`"+`
        Meta        map[string]any `+"`json:\"_meta,omitempty\"`"+`
        InputSchema map[string]any `+"`json:\"inputSchema\"`"+`
    } `+"`json:\"tools\"`"+`
}
json.Unmarshal(res.Raw, &out)
for _, t := range out.Tools {
    props := t.InputSchema["properties"].(map[string]any)
    fmt.Printf("  %s\n", t.Name)
    fmt.Printf("    _meta:      %v\n", t.Meta)
    fmt.Printf("    metric:     %v\n", props["metric"])
    fmt.Printf("    periodType: %v\n", props["periodType"])
}`,
	).Run(func(ctx demokit.StepContext) *demokit.StepResult {
		res, err := c.Call("tools/list", map[string]any{})
		if err != nil {
			fmt.Printf("    ERROR: %v\n", err)
			return nil
		}
		var out struct {
			Tools []struct {
				Name        string         `json:"name"`
				Meta        map[string]any `json:"_meta,omitempty"`
				InputSchema map[string]any `json:"inputSchema"`
			} `json:"tools"`
		}
		if err := json.Unmarshal(res.Raw, &out); err != nil {
			fmt.Printf("    ERROR decoding tools/list: %v\n", err)
			return nil
		}
		for _, t := range out.Tools {
			pretty, _ := json.MarshalIndent(t.Meta, "      ", "  ")
			fmt.Printf("    %s\n      _meta: %s\n", t.Name, string(pretty))
			props, _ := t.InputSchema["properties"].(map[string]any)
			for _, key := range []string{"metric", "periodType"} {
				if v, ok := props[key]; ok {
					vpretty, _ := json.MarshalIndent(v, "        ", "  ")
					fmt.Printf("      inputSchema.properties.%s:\n        %s\n", key, string(vpretty))
				}
			}
		}
		return nil
	})

	step3 := demo.Step("tools/call get-cohort-data {} — the 12×12 heatmap payload").
		Arrow("Host", "Server", "tools/call get-cohort-data {}").
		DashedArrow("Server", "Host", "ToolResult{content[0].text, structuredContent: {cohorts, periods, ...}}").
		Note("Empty arguments → the handler applies the schema defaults (metric=\"retention\", periodType=\"monthly\", cohortCount=12, maxPeriods=12) and runs a seeded exponential-decay generator to produce 12 cohorts × 12 period columns of retention data. The handler returns BOTH a text summary in content[0].text (for non-Apps hosts) and the structured payload (for the iframe). The walkthrough prints just the shape — dumping the full ~1000-number cell matrix would drown the wire detail.")
	common.WireRecipe(step3,
		`curl -s -X POST `+serverURL+`/mcp \
  -H "Mcp-Session-Id: $SID" \
  -H 'Content-Type: application/json' \
  -H 'Accept: text/event-stream, application/json' \
  -d '{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"get-cohort-data","arguments":{}}}' \
  | jq '.result | { content_text: .content[0].text, shape: { cohorts: (.structuredContent.cohorts | length), periods: (.structuredContent.periods | length), cells_in_first_cohort: (.structuredContent.cohorts[0].cells | length) }, sample_cell: .structuredContent.cohorts[0].cells[3] }'`,
		`tr, _ := c.ToolCallFull("get-cohort-data", map[string]any{})
sc := tr.StructuredContent.(map[string]any)
fmt.Printf("text summary: %s\n", tr.Content[0].Text)
fmt.Printf("cohorts:      %d\n", len(sc["cohorts"].([]any)))
fmt.Printf("periods:      %d\n", len(sc["periods"].([]any)))
fmt.Printf("metric:       %v\n", sc["metric"])`,
	).Run(func(ctx demokit.StepContext) *demokit.StepResult {
		tr, err := c.ToolCallFull("get-cohort-data", map[string]any{})
		if err != nil {
			fmt.Printf("    ERROR: %v\n", err)
			return nil
		}
		if len(tr.Content) > 0 {
			fmt.Printf("    content[0].text:\n")
			for _, line := range common.SplitLines(tr.Content[0].Text) {
				fmt.Printf("      %s\n", line)
			}
		}
		sc, _ := tr.StructuredContent.(map[string]any)
		if sc == nil {
			fmt.Printf("    ERROR: no structuredContent on tool result\n")
			return nil
		}
		fmt.Printf("    structuredContent shape:\n")
		fmt.Printf("      cohorts                = %d\n", lengthOf(sc, "cohorts"))
		fmt.Printf("      periods                = %d\n", lengthOf(sc, "periods"))
		fmt.Printf("      periodLabels           = %d\n", lengthOf(sc, "periodLabels"))
		if v, ok := sc["metric"]; ok {
			fmt.Printf("      metric                 = %v\n", v)
		}
		if v, ok := sc["periodType"]; ok {
			fmt.Printf("      periodType             = %v\n", v)
		}
		cohorts, _ := sc["cohorts"].([]any)
		if len(cohorts) > 0 {
			first, _ := cohorts[0].(map[string]any)
			cells, _ := first["cells"].([]any)
			fmt.Printf("      cohorts[0].cells       = %d\n", len(cells))
			if len(cells) > 3 {
				sample, _ := json.MarshalIndent(cells[3], "        ", "  ")
				fmt.Printf("      cohorts[0].cells[3]:\n        %s\n", string(sample))
			}
		}
		return nil
	})

	step4 := demo.Step("resources/read — the iframe HTML the App ships in").
		Arrow("Host", "Server", "resources/read { uri: ui://get-cohort-data/mcp-app.html }").
		DashedArrow("Server", "Host", "Contents[0].text + Contents[0]._meta").
		Note("Pulls the iframe HTML the App loads inside. The walkthrough reports just the byte count (the body is upstream's verbatim bundled JS+HTML; not interesting to dump on the wire) plus whatever `_meta` the resource carries. cohort-heatmap's `_meta` is bare — compare to sheet-music's `_meta.ui.csp.connectDomains` (soundfont CDN) and transcript's `_meta.ui.permissions.microphone` for the per-fixture `_meta` story.")
	common.WireRecipe(step4,
		`curl -s -X POST `+serverURL+`/mcp \
  -H "Mcp-Session-Id: $SID" \
  -H 'Content-Type: application/json' \
  -H 'Accept: text/event-stream, application/json' \
  -d '{"jsonrpc":"2.0","id":4,"method":"resources/read","params":{"uri":"ui://get-cohort-data/mcp-app.html"}}' \
  | jq '.result.contents[0] | { mimeType, bytes: (.text | length), _meta }'`,
		`var raw struct {
    Contents []struct {
        URI      string          `+"`json:\"uri\"`"+`
        MimeType string          `+"`json:\"mimeType\"`"+`
        Text     string          `+"`json:\"text\"`"+`
        Meta     json.RawMessage `+"`json:\"_meta\"`"+`
    } `+"`json:\"contents\"`"+`
}
res, _ := c.Call("resources/read", map[string]any{
    "uri": "ui://get-cohort-data/mcp-app.html",
})
json.Unmarshal(res.Raw, &raw)
fmt.Printf("mimeType: %s\n", raw.Contents[0].MimeType)
fmt.Printf("bytes:    %d\n", len(raw.Contents[0].Text))
fmt.Printf("_meta:    %s\n", string(raw.Contents[0].Meta))`,
	).Run(func(ctx demokit.StepContext) *demokit.StepResult {
		res, err := c.Call("resources/read", map[string]any{
			"uri": "ui://get-cohort-data/mcp-app.html",
		})
		if err != nil {
			fmt.Printf("    ERROR: %v\n", err)
			return nil
		}
		var raw struct {
			Contents []struct {
				URI      string          `json:"uri"`
				MimeType string          `json:"mimeType"`
				Text     string          `json:"text"`
				Meta     json.RawMessage `json:"_meta"`
			} `json:"contents"`
		}
		if err := json.Unmarshal(res.Raw, &raw); err != nil {
			fmt.Printf("    ERROR decoding resources/read: %v\n", err)
			return nil
		}
		if len(raw.Contents) == 0 {
			fmt.Printf("    no contents returned\n")
			return nil
		}
		c0 := raw.Contents[0]
		fmt.Printf("    uri:      %s\n", c0.URI)
		fmt.Printf("    mimeType: %s\n", c0.MimeType)
		fmt.Printf("    bytes:    %d  (iframe HTML+JS bundle)\n", len(c0.Text))
		if len(c0.Meta) > 0 {
			pretty, _ := json.MarshalIndent(json.RawMessage(c0.Meta), "      ", "  ")
			fmt.Printf("    _meta:\n      %s\n", string(pretty))
		} else {
			fmt.Printf("    _meta:    <none>  (no csp / permissions declared)\n")
		}
		return nil
	})

	demo.Section("What the App iframe does with all this",
		"The host → iframe handoff mechanics (`tools/call` → `resources/read` → sandboxed iframe → `postMessage`) are covered once in [The basic-host bridge dance](../README.md#the-basic-host-bridge-dance). Steps 1-4 above are the floor every MCP Apps interaction starts from.",
		"",
		"cohort-heatmap's iframe sits at the **moderate** end of the App-ness spectrum. The bridge calls its App SDK makes:",
		"",
		"- `app.ontoolresult` — unpacks `result.structuredContent` into the typed `CohortData` shape; the heatmap renders from `.cohorts` / `.periods` / `.periodLabels`.",
		"- `app.callServerTool({name: \"get-cohort-data\", arguments: {metric, periodType, ...}})` on every filter change — the two `<select>` dropdowns (Metric, PeriodType) drive a React effect that re-fetches via the bridge. Each dropdown change is a fresh `tools/call` round-trip through the bridge.",
		"- `app.getHostContext` + `app.onhostcontextchanged` — pulls host theming (theme, safe-area insets, display mode) so the heatmap chrome adapts.",
		"",
		"NO `app.registerTool` (the model can't drive the heatmap directly — it picks inputs and reads the chart), NO `app.updateModelContext` (the user fiddling with dropdowns doesn't push state back). Compare with `quickstart` (bare minimum, no host context) and `budget-allocator` (rich — 5 registered tools + model context updates).",
	)

	demo.Section("Where to look in the code",
		"- `main.go` — the fixture. ~200 lines: one TypedAppTool + the data generator (port of upstream's `generateCohortData` with a PCG seed for visual stability).",
		"- `walkthrough.go` — this file. Each step's curl + Go recipe is the canonical wire reproduction.",
		"- `../README.md` — narrative + screenshots + the [Other ways to test a fixture](../README.md#other-ways-to-test-a-fixture) guide.",
		"- Upstream's iframe source: `/tmp/ext-apps/examples/cohort-heatmap-server/src/mcp-app.tsx` — the React App that drives `useApp` + `callServerTool` + `getHostContext`.",
	)

	_ = step1
	_ = step2
	_ = step3
	_ = step4

	common.SetupRenderer(demo)
	demo.Execute()
}

// lengthOf returns the size of a nested array field without panicking on
// missing keys / wrong types. Returns 0 when the key is absent or the
// value isn't a JSON array.
func lengthOf(m map[string]any, key string) int {
	if v, ok := m[key].([]any); ok {
		return len(v)
	}
	return 0
}
