# Generated by scripts/gen_conf_paths.py from conformance/local-suites.yaml.
# Do not edit by hand. Update the YAML, then run:
#   uv run scripts/gen_conf_paths.py --write
# CI's check-local-suites-stale runs the generator in --check mode and
# fails if this file disagrees with the YAML.
#
# REPO_ROOT must be defined by the including Makefile before this file is
# included. conformance/Makefile sets it as $(abspath $(CONFORMANCE_DIR)/..).

MCPCONFORMANCE_AUTH_PATH        ?= $(abspath $(REPO_ROOT)/../conf-pending)
MCPCONFORMANCE_CLIENT_PATH      ?= $(abspath $(REPO_ROOT)/../conf-upstream-main)
MCPCONFORMANCE_FILE_INPUTS_PATH ?= $(abspath $(REPO_ROOT)/../conf-pending)
MCPCONFORMANCE_MRTR_PATH        ?= $(abspath $(REPO_ROOT)/../conf-upstream-main)
MCPCONFORMANCE_SKILLS_PATH      ?= $(abspath $(REPO_ROOT)/../conf-skills)
MCPCONFORMANCE_STATELESS_PATH   ?= $(abspath $(REPO_ROOT)/../conf-upstream-main)
MCPCONFORMANCE_TASKS_V2_PATH    ?= $(abspath $(REPO_ROOT)/../conf-upstream-main)
