# Generated by scripts/gen_conf_paths.py from conformance/local-suites.yaml.
# Do not edit by hand. Update the YAML, then run:
#   uv run scripts/gen_conf_paths.py --write
# CI's check-local-suites-stale runs the generator in --check mode and
# fails if this file disagrees with the YAML.
#
# Sourced by the runner-agnostic conformance scripts (conformance/scripts/
# conf-*.sh). REPO_ROOT must be exported by the sourcing script first. Each
# `:="${...}"` honors a pre-set env var (per-invocation override) and
# otherwise falls back to the sibling conf-* worktree default.

: "${MCPCONFORMANCE_AUTH_PATH:="$REPO_ROOT/../conf-pending"}"
: "${MCPCONFORMANCE_FILE_INPUTS_PATH:="$REPO_ROOT/../conf-pending"}"
: "${MCPCONFORMANCE_MRTR_PATH:="$REPO_ROOT/../conf-upstream-main"}"
: "${MCPCONFORMANCE_SKILLS_PATH:="$REPO_ROOT/../conf-skills"}"
: "${MCPCONFORMANCE_STATELESS_PATH:="$REPO_ROOT/../conf-upstream-main"}"
: "${MCPCONFORMANCE_TASKS_V2_PATH:="$REPO_ROOT/../conf-upstream-main"}"
