// Package runtime provides thin helpers imported by code generated by protoc-gen-go-mcp.
// Keep this package minimal — every dependency here is a transitive dep for all generated code.
package runtime

import (
	"encoding/json"
	"fmt"

	"github.com/panyam/mcpkit/core"
	"github.com/panyam/protokit/fields"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

// Default protojson options used by generated code.
var (
	unmarshalOpts = protojson.UnmarshalOptions{DiscardUnknown: true}
	marshalOpts   = protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}
)

// BindProto unmarshals MCP tool request arguments into a proto message.
// Arguments arrive as JSON (from the LLM) and are decoded via protojson.
func BindProto(req core.ToolRequest, msg proto.Message) error {
	raw := req.Arguments
	if len(raw) == 0 || string(raw) == "null" {
		return nil // empty args → zero-value proto
	}

	// MCP arguments arrive as a JSON object. protojson expects the same.
	return unmarshalOpts.Unmarshal(raw, msg)
}

// ProtoTextResult marshals a proto message to JSON and returns it as a TextResult.
func ProtoTextResult(msg proto.Message) (core.ToolResult, error) {
	data, err := marshalOpts.Marshal(msg)
	if err != nil {
		return core.ErrorResult(fmt.Sprintf("failed to marshal response: %v", err)), nil
	}
	return core.TextResult(string(data)), nil
}

// ProtoStructuredResult marshals a proto message and returns it as a StructuredResult.
// The text field contains the JSON string; structuredContent contains the parsed object.
func ProtoStructuredResult(msg proto.Message) (core.ToolResult, error) {
	data, err := marshalOpts.Marshal(msg)
	if err != nil {
		return core.ErrorResult(fmt.Sprintf("failed to marshal response: %v", err)), nil
	}

	// Parse into map for structuredContent.
	var structured any
	if err := json.Unmarshal(data, &structured); err != nil {
		return core.ErrorResult(fmt.Sprintf("failed to parse response: %v", err)), nil
	}

	return core.StructuredResult(string(data), structured), nil
}

// ProtoResourceResult marshals a proto message to JSON and returns it as a ResourceResult
// with the given URI and MIME type.
func ProtoResourceResult(msg proto.Message, uri, mimeType string) (core.ResourceResult, error) {
	data, err := marshalOpts.Marshal(msg)
	if err != nil {
		return core.ResourceResult{}, fmt.Errorf("failed to marshal resource: %w", err)
	}
	return core.ResourceResult{
		Contents: []core.ResourceReadContent{{
			URI:      uri,
			MimeType: mimeType,
			Text:     string(data),
		}},
	}, nil
}

// BindParams populates a proto message from URI template parameters.
// Each key is a field path (dot-separated for nested fields, e.g. "pos.q")
// and each string value is coerced to the target field type.
func BindParams(params map[string]string, msg proto.Message) error {
	return fields.PopulateFromMap(msg, params)
}

// RPCError wraps an RPC error as an MCP error result.
// The isError flag is set so the LLM knows the call failed.
func RPCError(err error) (core.ToolResult, error) {
	return core.ErrorResult(err.Error()), nil
}
