// Package runtime provides helpers imported by code generated by protoc-gen-go-mcp.
//
// These functions handle the boundary between MCP request/response types and
// proto messages:
//
//   - [BindProto]: unmarshal MCP tool arguments (JSON) into a proto request
//   - [BindParams]: populate a proto request from URI template parameters
//   - [BindPromptArgs]: populate a proto request from prompt argument values
//   - [ProtoTextResult]: marshal a proto response as MCP text content
//   - [ProtoStructuredResult]: marshal as MCP structured content
//   - [ProtoSummaryStructuredResult]: structured content with rendered summary template
//   - [ProtoResourceResult]: marshal as MCP resource content
//   - [ProtoPromptResult]: marshal as MCP prompt messages
//   - [RPCError]: convert errors (including gRPC status with details) to MCP error results
//
// Keep this package minimal — every dependency here is a transitive dep for
// all consumers of generated code.
package runtime

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/panyam/mcpkit/core"
	"github.com/panyam/protokit/fields"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// Default protojson options used by generated code.
var (
	unmarshalOpts = protojson.UnmarshalOptions{DiscardUnknown: true}
	marshalOpts   = protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}
)

// BindProto unmarshals MCP tool request arguments into a proto message.
// Arguments arrive as JSON (from the LLM) and are decoded via protojson.
func BindProto(req core.ToolRequest, msg proto.Message) error {
	raw := req.Arguments
	if len(raw) == 0 || string(raw) == "null" {
		return nil // empty args → zero-value proto
	}

	// MCP arguments arrive as a JSON object. protojson expects the same.
	return unmarshalOpts.Unmarshal(raw, msg)
}

// ProtoTextResult marshals a proto message to JSON and returns it as a TextResult.
func ProtoTextResult(msg proto.Message) (core.ToolResult, error) {
	data, err := marshalOpts.Marshal(msg)
	if err != nil {
		return core.ErrorResult(fmt.Sprintf("failed to marshal response: %v", err)), nil
	}
	return core.TextResult(string(data)), nil
}

// ProtoStructuredResult marshals a proto message and returns it as a StructuredResult.
// The text field contains the JSON string; structuredContent contains the parsed object.
func ProtoStructuredResult(msg proto.Message) (core.ToolResult, error) {
	data, err := marshalOpts.Marshal(msg)
	if err != nil {
		return core.ErrorResult(fmt.Sprintf("failed to marshal response: %v", err)), nil
	}

	// Parse into map for structuredContent.
	var structured any
	if err := json.Unmarshal(data, &structured); err != nil {
		return core.ErrorResult(fmt.Sprintf("failed to parse response: %v", err)), nil
	}

	return core.StructuredResult(string(data), structured), nil
}

// ProtoResourceResult marshals a proto message and returns it as a ResourceResult
// with the given URI and MIME type.
//
// For JSON resources (application/json), the message is serialized via protojson.
// For non-JSON resources (text/html, text/yaml, text/markdown, etc.), the function
// extracts a raw string from a single "content" field if present. This ensures
// the MCP resource text contains the actual content, not a JSON wrapper — matching
// what a hand-written resource handler would return.
func ProtoResourceResult(msg proto.Message, uri, mimeType string) (core.ResourceResult, error) {
	var text string
	if mimeType != "application/json" {
		// Try to extract raw content for non-JSON resources.
		if raw, ok := extractSingleStringField(msg); ok {
			text = raw
		}
	}
	if text == "" {
		// Fall back to JSON serialization (for JSON resources or messages
		// without a single string field).
		data, err := marshalOpts.Marshal(msg)
		if err != nil {
			return core.ResourceResult{}, fmt.Errorf("failed to marshal resource: %w", err)
		}
		text = string(data)
	}
	return core.ResourceResult{
		Contents: []core.ResourceReadContent{{
			URI:      uri,
			MimeType: mimeType,
			Text:     text,
		}},
	}, nil
}

// extractSingleStringField checks if a proto message has exactly one populated
// field and that field is a string. Returns the string value if so.
// Used by ProtoResourceResult to extract raw content for non-JSON MIME types
// (e.g., a SlideContentResource with a single "content" field should return
// the HTML, not {"content":"..."}).
//
// Returns false if the message has zero fields, multiple fields, or a single
// non-string field — all of which fall through to JSON serialization.
func extractSingleStringField(msg proto.Message) (string, bool) {
	ref := msg.ProtoReflect()
	var result string
	var totalFields int
	var isString bool
	ref.Range(func(fd protoreflect.FieldDescriptor, v protoreflect.Value) bool {
		totalFields++
		if fd.Kind() == protoreflect.StringKind {
			result = v.String()
			isString = true
		}
		return true
	})
	if totalFields == 1 && isString && result != "" {
		return result, true
	}
	return "", false
}

// ProtoPromptResult marshals a proto message to JSON and returns it as a
// PromptResult with a single assistant text message.
func ProtoPromptResult(msg proto.Message) (core.PromptResult, error) {
	data, err := marshalOpts.Marshal(msg)
	if err != nil {
		return core.PromptResult{}, fmt.Errorf("failed to marshal prompt response: %w", err)
	}
	return core.PromptResult{
		Messages: []core.PromptMessage{{
			Role:    "assistant",
			Content: core.Content{Type: "text", Text: string(data)},
		}},
	}, nil
}

// BindPromptArgs populates a proto message from prompt argument values.
// Prompt arguments arrive as map[string]any (JSON-decoded). Each value is
// re-marshaled to JSON and the full map is unmarshaled via protojson.
func BindPromptArgs(args map[string]any, msg proto.Message) error {
	if len(args) == 0 {
		return nil
	}
	data, err := json.Marshal(args)
	if err != nil {
		return fmt.Errorf("marshal prompt args: %w", err)
	}
	return unmarshalOpts.Unmarshal(data, msg)
}

// ProtoSummaryStructuredResult marshals a proto message and returns it as a
// StructuredResult where the text content is a rendered summary template.
// The template uses {field_name} placeholders interpolated from the response
// message's JSON representation.
func ProtoSummaryStructuredResult(msg proto.Message, summaryTemplate string) (core.ToolResult, error) {
	data, err := marshalOpts.Marshal(msg)
	if err != nil {
		return core.ErrorResult(fmt.Sprintf("failed to marshal response: %v", err)), nil
	}

	// Parse into map for both structured content and summary interpolation.
	var fields map[string]any
	if err := json.Unmarshal(data, &fields); err != nil {
		return core.ErrorResult(fmt.Sprintf("failed to parse response: %v", err)), nil
	}

	// Render summary by replacing {field} placeholders.
	summary := renderSummary(summaryTemplate, fields)

	return core.StructuredResult(summary, fields), nil
}

// renderSummary replaces {field_name} placeholders in a template with values
// from a map. Unknown fields are left as-is.
func renderSummary(tmpl string, fields map[string]any) string {
	result := tmpl
	for key, val := range fields {
		result = strings.ReplaceAll(result, "{"+key+"}", fmt.Sprintf("%v", val))
	}
	return result
}

// BindParams populates a proto message from URI template parameters.
// Each key is a field path (dot-separated for nested fields, e.g. "pos.q")
// and each string value is coerced to the target field type.
func BindParams(params map[string]string, msg proto.Message) error {
	return fields.PopulateFromMap(msg, params)
}

// BindElicitResult unmarshals an elicitation result content map into a typed
// proto message. Returns a pointer to the populated message.
//
// Usage in generated code:
//
//	approval, err := runtime.BindElicitResult[SummaryApproval](result.Content)
//	// approval is *SummaryApproval
func BindElicitResult[T any, PT interface {
	*T
	proto.Message
}](content map[string]any) (PT, error) {
	msg := PT(new(T))
	if len(content) == 0 {
		return msg, nil
	}
	data, err := json.Marshal(content)
	if err != nil {
		return nil, fmt.Errorf("marshal elicit content: %w", err)
	}
	if err := unmarshalOpts.Unmarshal(data, msg); err != nil {
		return nil, err
	}
	return msg, nil
}

// RPCError wraps an RPC error as an MCP error result.
// If the error is a gRPC status error, the status code and any attached
// details (proto Any messages) are extracted and returned as structured
// error content so agents can parse and recover programmatically.
// For non-gRPC errors, falls back to a plain text error result.
func RPCError(err error) (core.ToolResult, error) {
	st, ok := status.FromError(err)
	if !ok {
		return core.ErrorResult(err.Error()), nil
	}

	// Build structured error with code + message + details.
	errData := map[string]any{
		"code":    st.Code().String(),
		"message": st.Message(),
	}

	// Extract status details as JSON objects.
	if details := st.Details(); len(details) > 0 {
		detailList := make([]any, 0, len(details))
		for _, d := range details {
			if pm, ok := d.(proto.Message); ok {
				data, err := marshalOpts.Marshal(pm)
				if err == nil {
					var parsed any
					if json.Unmarshal(data, &parsed) == nil {
						detailList = append(detailList, parsed)
						continue
					}
				}
			}
			// Fallback for non-proto or unmarshal failure.
			detailList = append(detailList, fmt.Sprintf("%v", d))
		}
		errData["details"] = detailList
	}

	return core.StructuredError(st.Message(), errData), nil
}
