#!/usr/bin/env python3
"""Generate conformance/path-defaults.mk from conformance/local-suites.yaml.

The YAML manifest is the single source of truth for which fork branch +
default checkout path each testconf-* suite expects. This script reads
the manifest and emits a make snippet:

    MCPCONFORMANCE_TASKS_V2_PATH    ?= $(abspath $(REPO_ROOT)/../conf-tasks-mrtr)
    MCPCONFORMANCE_MRTR_PATH        ?= $(abspath $(REPO_ROOT)/../conf-tasks-mrtr)
    ...

conformance/Makefile includes the result. The `?=` semantics preserve
per-invocation overrides (MCPCONFORMANCE_*=... just testconf-*), so this
restructure doesn't change developer ergonomics — it just removes the
duplication between YAML and Makefile.

Modes:
    --check    Compute the would-be output and compare against
               conformance/path-defaults.mk. Exit 1 on drift (case E in
               scripts/check_local_suites.py).
    --write    Generate conformance/path-defaults.mk in place. Use this
               after editing the YAML.
    --print    Emit to stdout. Useful for debugging.

Default mode is --check so CI catches drift on every PR.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write(
        "gen_conf_paths: PyYAML not available. Install with: pip install pyyaml\n"
    )
    sys.exit(2)


REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "conformance" / "local-suites.yaml"
OUTPUT = REPO_ROOT / "conformance" / "path-defaults.mk"

HEADER = """\
# Generated by scripts/gen_conf_paths.py from conformance/local-suites.yaml.
# Do not edit by hand. Update the YAML, then run:
#   uv run scripts/gen_conf_paths.py --write
# CI's check-local-suites-stale runs the generator in --check mode and
# fails if this file disagrees with the YAML.
#
# REPO_ROOT must be defined by the including Makefile before this file is
# included. conformance/Makefile sets it as $(abspath $(CONFORMANCE_DIR)/..).
"""


def render(manifest_path: Path) -> str:
    try:
        manifest = yaml.safe_load(manifest_path.read_text())
    except yaml.YAMLError as exc:
        sys.stderr.write(f"gen_conf_paths: {manifest_path}: invalid YAML: {exc}\n")
        sys.exit(2)
    if not isinstance(manifest, dict):
        sys.stderr.write(f"gen_conf_paths: {manifest_path}: top-level value must be a mapping\n")
        sys.exit(2)

    suites = manifest.get("suites")
    if not isinstance(suites, list):
        sys.stderr.write(f"gen_conf_paths: {manifest_path}: `suites` must be a list\n")
        sys.exit(2)

    rows: list[tuple[str, str]] = []
    for entry in suites:
        source = entry.get("source")
        if not source:
            continue
        path_var = source.get("path_var")
        default_path = source.get("default_path")
        if not path_var or not default_path:
            sys.stderr.write(
                f"gen_conf_paths: {entry.get('suite', '<unknown>')} source missing path_var or default_path\n"
            )
            sys.exit(2)
        rows.append((path_var, default_path))

    # Deduplicate by (path_var, default_path) since multiple suites can share
    # the same env var (testconf-tasks-v2 + testconf-mrtr both default to
    # ../conf-tasks-mrtr but use different vars — keep both vars listed).
    seen: set[str] = set()
    unique: list[tuple[str, str]] = []
    for var, path in rows:
        if var in seen:
            continue
        seen.add(var)
        unique.append((var, path))

    # Sort by var name for deterministic output.
    unique.sort(key=lambda r: r[0])

    width = max(len(var) for var, _ in unique) if unique else 0
    lines = [HEADER]
    for var, path in unique:
        lines.append(f"{var:<{width}} ?= $(abspath $(REPO_ROOT)/{path})")
    lines.append("")  # trailing newline
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true", help="diff against the committed file, exit 1 on drift (default)")
    group.add_argument("--write", action="store_true", help="generate the file in place")
    group.add_argument("--print", action="store_true", dest="print_out", help="emit to stdout")
    args = parser.parse_args()

    rendered = render(MANIFEST)

    if args.write:
        OUTPUT.write_text(rendered)
        print(f"gen_conf_paths: wrote {OUTPUT.relative_to(REPO_ROOT)}")
        return 0

    if args.print_out:
        sys.stdout.write(rendered)
        return 0

    # Default: --check.
    if not OUTPUT.exists():
        sys.stderr.write(
            f"gen_conf_paths: {OUTPUT.relative_to(REPO_ROOT)} does not exist. "
            f"Run: uv run scripts/gen_conf_paths.py --write\n"
        )
        return 1
    committed = OUTPUT.read_text()
    if committed != rendered:
        sys.stderr.write(
            f"gen_conf_paths: case E drift: {OUTPUT.relative_to(REPO_ROOT)} is out of sync with the YAML.\n"
            f"                Run: uv run scripts/gen_conf_paths.py --write\n"
        )
        return 1
    print(f"gen_conf_paths: {OUTPUT.relative_to(REPO_ROOT)} in sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
