#!/bin/sh
# Pre-push hook for mcpkit.
#
# Runs sub-module go.mod verification + full test suite before pushing. If
# the only files changed in the commits being pushed are test reports
# (tests/reports/*), the test stage is skipped — those artifacts are
# regenerated by `make testall` and don't affect source behavior, so
# re-running tests would be a waste.
#
# Installed by `make setup-hooks`. Edit this file in the repo, then
# `make setup-hooks` to reinstall.

set -e
cd "$(git rev-parse --show-toplevel)"

# Determine the commit range being pushed. Prefer @{upstream}; fall back to
# origin/main; if both fail (detached HEAD, fresh branch with no remote),
# treat as "unknown range" and run the full check to be safe.
range=""
if git rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' >/dev/null 2>&1; then
    range="@{upstream}..HEAD"
elif git rev-parse --verify origin/main >/dev/null 2>&1; then
    range="origin/main..HEAD"
fi

changed=""
if [ -n "$range" ]; then
    changed="$(git diff --name-only "$range" 2>/dev/null || true)"
fi

# Determine whether tests need to run. Default: yes.
needs_tests=1

if [ -n "$changed" ]; then
    # Walk the changed file list. If every file matches a skip pattern,
    # flip needs_tests to 0. If any file doesn't match, keep it at 1.
    all_skip=1
    for f in $changed; do
        case "$f" in
            tests/reports/*)
                ;;
            *)
                all_skip=0
                break
                ;;
        esac
    done
    if [ $all_skip -eq 1 ]; then
        needs_tests=0
    fi
fi

if [ $needs_tests -eq 0 ]; then
    echo "pre-push: only test-report changes detected, skipping test run"
    exit 0
fi

echo "Verifying sub-module go.mod..."
bash scripts/verify-submodule-deps.sh

echo "Running root module tests..."
go test ./...

echo "Running ext/auth tests..."
cd ext/auth && go test ./...
cd "$OLDPWD"

echo "Running ext/ui tests..."
cd ext/ui && go test ./...
cd "$OLDPWD"

echo "Running ext/protogen tests..."
cd ext/protogen && go test ./...
