package main

import booksv1 "github.com/panyam/mcpkit/examples/protogen/bookservice/gen/bookservice/v1"

// catalog is the in-memory book database. 200 books across 8 genres.
var catalog = []*booksv1.Book{
	// --- programming ---
	{Id: "1", Title: "The Go Programming Language", Author: "donovan-kernighan", Genre: "programming", Year: 2015, Rating: 4.5,
		Synopsis: "Comprehensive guide to Go covering the language spec, standard library, concurrency with goroutines and channels, interfaces, testing, and low-level programming."},
	{Id: "2", Title: "The Pragmatic Programmer", Author: "hunt-thomas", Genre: "programming", Year: 1999, Rating: 4.6,
		Synopsis: "Classic software engineering wisdom covering DRY, orthogonality, tracer bullets, domain languages, estimation, and pragmatic approaches to testing and debugging."},
	{Id: "3", Title: "Clean Code", Author: "martin-rc", Genre: "programming", Year: 2008, Rating: 4.3,
		Synopsis: "Principles for writing readable, maintainable code. Covers naming, functions, comments, formatting, error handling, unit testing, and refactoring with Java examples."},
	{Id: "4", Title: "Refactoring", Author: "fowler", Genre: "programming", Year: 2018, Rating: 4.5,
		Synopsis: "A catalog of refactoring techniques for improving the design of existing code. Covers code smells, composing methods, and simplifying conditional expressions."},
	{Id: "5", Title: "The Mythical Man-Month", Author: "brooks", Genre: "programming", Year: 1975, Rating: 4.3,
		Synopsis: "Classic essays on software engineering management. Introduces Brooks's Law, the surgical team model, and the second-system effect."},
	{Id: "6", Title: "Code Complete", Author: "mcconnell", Genre: "programming", Year: 2004, Rating: 4.4,
		Synopsis: "Encyclopedic guide to software construction covering design, coding, debugging, testing, and code tuning with practical checklists."},
	{Id: "7", Title: "Working Effectively with Legacy Code", Author: "feathers", Genre: "programming", Year: 2004, Rating: 4.4,
		Synopsis: "Strategies for safely modifying code without tests. Covers seams, dependency breaking techniques, and incremental test coverage."},
	{Id: "8", Title: "Programming Pearls", Author: "bentley", Genre: "programming", Year: 1999, Rating: 4.3,
		Synopsis: "Elegant solutions to real-world programming problems. Covers algorithm design, back-of-the-envelope calculations, and performance optimization."},
	{Id: "9", Title: "The Art of Unix Programming", Author: "raymond", Genre: "programming", Year: 2003, Rating: 4.2,
		Synopsis: "Unix design philosophy: simplicity, modularity, text streams, composition. Covers tool design, IPC, languages, and the cultural context of Unix."},
	{Id: "10", Title: "Effective Java", Author: "bloch", Genre: "programming", Year: 2018, Rating: 4.7,
		Synopsis: "Best practices for Java programming covering object creation, methods, generics, enums, lambdas, streams, concurrency, and serialization."},
	{Id: "11", Title: "JavaScript: The Good Parts", Author: "crockford", Genre: "programming", Year: 2008, Rating: 4.1,
		Synopsis: "Distills JavaScript to its elegant core. Covers functions, objects, inheritance, arrays, regular expressions, and the subset worth using."},
	{Id: "12", Title: "Python Cookbook", Author: "beazley-jones", Genre: "programming", Year: 2013, Rating: 4.4,
		Synopsis: "Recipes for common Python programming tasks covering data structures, iterators, functions, classes, modules, concurrency, and metaprogramming."},
	{Id: "13", Title: "Rust Programming Language", Author: "klabnik-nichols", Genre: "programming", Year: 2019, Rating: 4.6,
		Synopsis: "Official Rust guide covering ownership, borrowing, lifetimes, pattern matching, traits, closures, smart pointers, concurrency, and unsafe code."},
	{Id: "14", Title: "Domain-Driven Design", Author: "evans", Genre: "programming", Year: 2003, Rating: 4.2,
		Synopsis: "Tackling complexity in software by aligning code with business domains. Covers bounded contexts, aggregates, entities, value objects, and ubiquitous language."},
	{Id: "15", Title: "Test-Driven Development", Author: "beck", Genre: "programming", Year: 2002, Rating: 4.3,
		Synopsis: "The red-green-refactor cycle explained through two extended examples. Covers test patterns, mock objects, and growing software guided by tests."},
	{Id: "16", Title: "Patterns of Enterprise Application Architecture", Author: "fowler", Genre: "programming", Year: 2002, Rating: 4.1,
		Synopsis: "Catalog of architectural patterns for enterprise applications: Active Record, Data Mapper, Unit of Work, Repository, and Service Layer."},
	{Id: "17", Title: "Head First Design Patterns", Author: "freeman-robson", Genre: "programming", Year: 2004, Rating: 4.5,
		Synopsis: "Approachable introduction to design patterns using visual learning. Covers Strategy, Observer, Decorator, Factory, Singleton, Command, and more."},
	{Id: "18", Title: "Release It!", Author: "nygard", Genre: "programming", Year: 2018, Rating: 4.5,
		Synopsis: "Production-ready software design patterns. Covers stability patterns (circuit breakers, bulkheads), capacity patterns, and deployment strategies."},
	{Id: "19", Title: "Continuous Delivery", Author: "humble-farley", Genre: "programming", Year: 2010, Rating: 4.3,
		Synopsis: "Automated deployment pipelines from commit to production. Covers build automation, testing strategies, release management, and infrastructure as code."},
	{Id: "20", Title: "Concurrency in Go", Author: "cox-buday", Genre: "programming", Year: 2017, Rating: 4.4,
		Synopsis: "Go concurrency patterns and primitives. Covers goroutines, channels, select, sync package, context, pipelines, fan-out/fan-in, and error handling."},

	// --- systems ---
	{Id: "21", Title: "Designing Data-Intensive Applications", Author: "kleppmann", Genre: "systems", Year: 2017, Rating: 4.8,
		Synopsis: "Internals of databases, stream and batch processing, distributed systems. Covers replication, partitioning, transactions, consensus, and data architecture trade-offs."},
	{Id: "22", Title: "Site Reliability Engineering", Author: "beyer-jones-petoff-murphy", Genre: "systems", Year: 2016, Rating: 4.4,
		Synopsis: "Google's approach to running production systems. Covers SLOs, error budgets, toil reduction, monitoring, incident response, and capacity planning."},
	{Id: "23", Title: "Distributed Systems", Author: "van-steen-tanenbaum", Genre: "systems", Year: 2017, Rating: 4.2,
		Synopsis: "Comprehensive textbook covering architectures, processes, communication, naming, coordination, consistency, replication, and fault tolerance."},
	{Id: "24", Title: "Database Internals", Author: "petrov", Genre: "systems", Year: 2019, Rating: 4.6,
		Synopsis: "Internal workings of storage engines and distributed databases. Covers B-trees, LSM-trees, buffer management, leader election, and gossip protocols."},
	{Id: "25", Title: "Operating Systems: Three Easy Pieces", Author: "arpaci-dusseau", Genre: "systems", Year: 2018, Rating: 4.6,
		Synopsis: "Virtualization, concurrency, and persistence in operating systems. Covers processes, threads, locks, scheduling, paging, file systems, and I/O devices."},
	{Id: "26", Title: "Computer Networking: A Top-Down Approach", Author: "kurose-ross", Genre: "systems", Year: 2016, Rating: 4.3,
		Synopsis: "Network architecture from application layer down. Covers HTTP, DNS, TCP, UDP, IP, routing, link layer, wireless, multimedia, and network security."},
	{Id: "27", Title: "Systems Performance", Author: "gregg", Genre: "systems", Year: 2020, Rating: 4.7,
		Synopsis: "Performance analysis and tuning for Linux. Covers CPUs, memory, file systems, disks, networking, and tools like perf, ftrace, BPF, and eBPF."},
	{Id: "28", Title: "Building Microservices", Author: "newman", Genre: "systems", Year: 2021, Rating: 4.3,
		Synopsis: "Designing fine-grained systems. Covers decomposition, integration patterns, deployment, testing, monitoring, security, and organizational alignment."},
	{Id: "29", Title: "Kafka: The Definitive Guide", Author: "narkhede-shapira-palino", Genre: "systems", Year: 2021, Rating: 4.3,
		Synopsis: "Apache Kafka internals and operations. Covers producers, consumers, streams, connect, partitioning, replication, and exactly-once semantics."},
	{Id: "30", Title: "Understanding Distributed Systems", Author: "vitillo", Genre: "systems", Year: 2022, Rating: 4.5,
		Synopsis: "Practical guide to building reliable distributed systems. Covers communication, coordination, scalability, resiliency, and maintainability patterns."},
	{Id: "31", Title: "The Art of Scalability", Author: "abbott-fisher", Genre: "systems", Year: 2015, Rating: 4.1,
		Synopsis: "Scaling organizations and technology. Covers the scale cube (X/Y/Z splitting), caching, database scaling, cloud architecture, and organizational models."},
	{Id: "32", Title: "Web Scalability for Startup Engineers", Author: "ejsmont", Genre: "systems", Year: 2015, Rating: 4.2,
		Synopsis: "Practical scaling techniques for web applications. Covers caching, queues, data partitioning, search, and handling growth from startup to scale."},
	{Id: "33", Title: "Observability Engineering", Author: "majors-fong-jones-miranda", Genre: "systems", Year: 2022, Rating: 4.4,
		Synopsis: "Beyond monitoring: structured events, distributed tracing, SLOs, debugging in production, and building an observability-driven development culture."},
	{Id: "34", Title: "Cloud Native Patterns", Author: "davis", Genre: "systems", Year: 2019, Rating: 4.1,
		Synopsis: "Patterns for cloud-native applications. Covers event-driven architecture, serverless, containers, service mesh, and twelve-factor methodology."},
	{Id: "35", Title: "Infrastructure as Code", Author: "morris", Genre: "systems", Year: 2020, Rating: 4.2,
		Synopsis: "Managing infrastructure through automation. Covers Terraform, configuration management, immutable infrastructure, GitOps, and testing infrastructure."},

	// --- cs-theory ---
	{Id: "36", Title: "Structure and Interpretation of Computer Programs", Author: "abelson-sussman", Genre: "cs-theory", Year: 1996, Rating: 4.7,
		Synopsis: "Foundational CS text using Scheme to explore abstraction, recursion, higher-order functions, metalinguistic abstraction, and interpreter design."},
	{Id: "37", Title: "Introduction to Algorithms", Author: "cormen-leiserson-rivest-stein", Genre: "cs-theory", Year: 2009, Rating: 4.4,
		Synopsis: "The definitive algorithms textbook covering sorting, graph algorithms, dynamic programming, greedy algorithms, NP-completeness, and advanced data structures."},
	{Id: "38", Title: "Gödel, Escher, Bach", Author: "hofstadter", Genre: "cs-theory", Year: 1979, Rating: 4.7,
		Synopsis: "Exploration of consciousness, self-reference, and formal systems through mathematics, art, and music. Connects Gödel's incompleteness theorems with Escher and Bach."},
	{Id: "39", Title: "The Art of Computer Programming", Author: "knuth", Genre: "cs-theory", Year: 1997, Rating: 4.6,
		Synopsis: "Knuth's magnum opus on fundamental algorithms and analysis. Covers combinatorial algorithms, sorting, searching, and mathematical foundations of computing."},
	{Id: "40", Title: "Types and Programming Languages", Author: "pierce", Genre: "cs-theory", Year: 2002, Rating: 4.5,
		Synopsis: "Comprehensive introduction to type systems. Covers lambda calculus, simple types, subtyping, recursive types, polymorphism, and type reconstruction."},
	{Id: "41", Title: "Compilers: Principles, Techniques, and Tools", Author: "aho-lam-sethi-ullman", Genre: "cs-theory", Year: 2006, Rating: 4.3,
		Synopsis: "The Dragon Book: lexical analysis, parsing, syntax-directed translation, intermediate code generation, optimization, and code generation."},
	{Id: "42", Title: "Category Theory for Programmers", Author: "milewski", Genre: "cs-theory", Year: 2019, Rating: 4.4,
		Synopsis: "Category theory concepts for working programmers. Covers functors, natural transformations, monads, Yoneda lemma, and their programming analogues."},
	{Id: "43", Title: "Purely Functional Data Structures", Author: "okasaki", Genre: "cs-theory", Year: 1998, Rating: 4.3,
		Synopsis: "Persistent data structures in functional programming. Covers amortization, lazy evaluation, queues, heaps, random-access lists, and numerical representations."},
	{Id: "44", Title: "Concrete Mathematics", Author: "graham-knuth-patashnik", Genre: "cs-theory", Year: 1994, Rating: 4.5,
		Synopsis: "Mathematical foundations for computer science. Covers recurrences, sums, number theory, binomial coefficients, generating functions, and asymptotic analysis."},
	{Id: "45", Title: "The Little Schemer", Author: "friedman-felleisen", Genre: "cs-theory", Year: 1995, Rating: 4.4,
		Synopsis: "Recursive thinking through Socratic dialogue. Builds from basic list operations to Y combinator and meta-circular evaluators."},
	{Id: "46", Title: "Computability and Logic", Author: "boolos-burgess-jeffrey", Genre: "cs-theory", Year: 2007, Rating: 4.2,
		Synopsis: "Mathematical logic and computability theory. Covers Turing machines, recursive functions, Gödel numbering, incompleteness, and undecidability."},
	{Id: "47", Title: "Algorithm Design Manual", Author: "skiena", Genre: "cs-theory", Year: 2020, Rating: 4.5,
		Synopsis: "Practical algorithm design with a catalog of algorithmic problems. Covers graph traversal, combinatorial search, dynamic programming, and heuristics."},
	{Id: "48", Title: "Information Theory, Inference, and Learning Algorithms", Author: "mackay", Genre: "cs-theory", Year: 2003, Rating: 4.4,
		Synopsis: "Unified treatment of information theory and machine learning. Covers entropy, compression, noisy channels, Bayesian inference, and neural networks."},

	// --- ai-ml ---
	{Id: "49", Title: "Deep Learning", Author: "goodfellow-bengio-courville", Genre: "ai-ml", Year: 2016, Rating: 4.5,
		Synopsis: "Comprehensive deep learning textbook. Covers linear algebra foundations, MLPs, CNNs, RNNs, optimization, regularization, generative models, and research frontiers."},
	{Id: "50", Title: "Pattern Recognition and Machine Learning", Author: "bishop", Genre: "ai-ml", Year: 2006, Rating: 4.5,
		Synopsis: "Bayesian approach to pattern recognition. Covers probability distributions, linear models, neural networks, kernel methods, graphical models, and EM algorithm."},
	{Id: "51", Title: "Hands-On Machine Learning", Author: "geron", Genre: "ai-ml", Year: 2022, Rating: 4.6,
		Synopsis: "Practical ML with Scikit-Learn, Keras, and TensorFlow. Covers regression, classification, training deep nets, CNNs, RNNs, GANs, and reinforcement learning."},
	{Id: "52", Title: "Artificial Intelligence: A Modern Approach", Author: "russell-norvig", Genre: "ai-ml", Year: 2020, Rating: 4.4,
		Synopsis: "The standard AI textbook. Covers search, knowledge representation, planning, uncertain reasoning, learning, NLP, robotics, and philosophical foundations."},
	{Id: "53", Title: "Speech and Language Processing", Author: "jurafsky-martin", Genre: "ai-ml", Year: 2023, Rating: 4.5,
		Synopsis: "NLP and computational linguistics. Covers n-grams, neural language models, transformers, parsing, semantics, information extraction, and dialogue systems."},
	{Id: "54", Title: "Reinforcement Learning: An Introduction", Author: "sutton-barto", Genre: "ai-ml", Year: 2018, Rating: 4.5,
		Synopsis: "Foundational RL text. Covers MDPs, dynamic programming, Monte Carlo, temporal difference, policy gradient, deep RL, and multi-agent systems."},
	{Id: "55", Title: "The Elements of Statistical Learning", Author: "hastie-tibshirani-friedman", Genre: "ai-ml", Year: 2009, Rating: 4.5,
		Synopsis: "Statistical learning theory for data science. Covers linear methods, basis expansions, kernel smoothing, model assessment, ensemble methods, and neural nets."},
	{Id: "56", Title: "Probabilistic Machine Learning: An Introduction", Author: "murphy", Genre: "ai-ml", Year: 2022, Rating: 4.6,
		Synopsis: "Modern ML from a probabilistic perspective. Covers Bayesian inference, linear models, deep learning, sequence models, graph models, and causality."},
	{Id: "57", Title: "Natural Language Processing with Transformers", Author: "tunstall-von-werra-wolf", Genre: "ai-ml", Year: 2022, Rating: 4.4,
		Synopsis: "Building NLP applications with Hugging Face Transformers. Covers text classification, NER, question answering, summarization, generation, and model optimization."},
	{Id: "58", Title: "Designing Machine Learning Systems", Author: "huyen", Genre: "ai-ml", Year: 2022, Rating: 4.5,
		Synopsis: "Production ML system design. Covers data engineering, feature engineering, model development, deployment, monitoring, infrastructure, and MLOps practices."},
	{Id: "59", Title: "Machine Learning Engineering", Author: "burkov", Genre: "ai-ml", Year: 2020, Rating: 4.3,
		Synopsis: "From prototype to production ML. Covers data collection, feature engineering, model training, evaluation, deployment, monitoring, and maintenance at scale."},
	{Id: "60", Title: "Build a Large Language Model (From Scratch)", Author: "raschka", Genre: "ai-ml", Year: 2024, Rating: 4.5,
		Synopsis: "Step-by-step guide to building GPT-like models from scratch. Covers attention mechanisms, pretraining, finetuning, and RLHF with PyTorch implementation."},

	// --- security ---
	{Id: "61", Title: "The Web Application Hacker's Handbook", Author: "stuttard-pinto", Genre: "security", Year: 2011, Rating: 4.5,
		Synopsis: "Comprehensive web security testing guide. Covers authentication, session management, access controls, injection, XSS, CSRF, and application logic flaws."},
	{Id: "62", Title: "Cryptography Engineering", Author: "ferguson-schneier-kohno", Genre: "security", Year: 2010, Rating: 4.4,
		Synopsis: "Practical cryptography design. Covers block ciphers, hash functions, MACs, public key crypto, protocols, key management, and implementation pitfalls."},
	{Id: "63", Title: "Threat Modeling", Author: "shostack", Genre: "security", Year: 2014, Rating: 4.2,
		Synopsis: "Designing for security by identifying and mitigating threats early. Covers STRIDE, attack trees, data flow diagrams, and integrating security into development."},
	{Id: "64", Title: "Serious Cryptography", Author: "aumasson", Genre: "security", Year: 2017, Rating: 4.5,
		Synopsis: "Modern cryptography explained clearly. Covers randomness, block ciphers, stream ciphers, hash functions, RSA, elliptic curves, TLS, and quantum threats."},
	{Id: "65", Title: "Hacking: The Art of Exploitation", Author: "erickson", Genre: "security", Year: 2008, Rating: 4.4,
		Synopsis: "Low-level exploitation techniques. Covers buffer overflows, shellcode, format strings, network attacks, and countermeasures with hands-on C examples."},
	{Id: "66", Title: "The Tangled Web", Author: "zalewski", Genre: "security", Year: 2011, Rating: 4.3,
		Synopsis: "A guide to web browser security. Covers the same-origin policy, URL parsing, HTML parsing, CSS, JavaScript quirks, and content handling pitfalls."},
	{Id: "67", Title: "Practical Cloud Security", Author: "dotson", Genre: "security", Year: 2019, Rating: 4.1,
		Synopsis: "Securing cloud infrastructure. Covers identity management, network security, data protection, logging, incident response for AWS, GCP, and Azure."},
	{Id: "68", Title: "Identity and Data Security for Web Development", Author: "leblanc", Genre: "security", Year: 2016, Rating: 4.0,
		Synopsis: "Authentication and authorization for web apps. Covers passwords, OAuth, OpenID Connect, SAML, JWT, session management, and secure API design."},
	{Id: "69", Title: "Bulletproof SSL and TLS", Author: "ristic", Genre: "security", Year: 2017, Rating: 4.5,
		Synopsis: "Complete guide to deploying secure servers and web applications using SSL/TLS. Covers protocol details, certificate management, and configuration best practices."},
	{Id: "70", Title: "Zero Trust Networks", Author: "gilman-barth", Genre: "security", Year: 2017, Rating: 4.1,
		Synopsis: "Building secure systems without a trusted perimeter. Covers identity, device trust, application trust, network agents, and zero trust architecture."},

	// --- devops ---
	{Id: "71", Title: "The Phoenix Project", Author: "kim-behr-spafford", Genre: "devops", Year: 2013, Rating: 4.5,
		Synopsis: "DevOps as a novel. IT manager Bill saves his company by discovering the Three Ways: flow, feedback, and continuous learning."},
	{Id: "72", Title: "Accelerate", Author: "forsgren-humble-kim", Genre: "devops", Year: 2018, Rating: 4.5,
		Synopsis: "Research-backed DevOps practices. Covers deployment frequency, lead time, MTTR, change failure rate, and the capabilities that drive performance."},
	{Id: "73", Title: "The DevOps Handbook", Author: "kim-humble-debois-willis", Genre: "devops", Year: 2016, Rating: 4.4,
		Synopsis: "Practical companion to The Phoenix Project. Covers deployment pipelines, telemetry, feedback loops, organizational learning, and security integration."},
	{Id: "74", Title: "Kubernetes in Action", Author: "luksa", Genre: "devops", Year: 2018, Rating: 4.5,
		Synopsis: "Comprehensive Kubernetes guide. Covers pods, services, deployments, volumes, ConfigMaps, Secrets, RBAC, StatefulSets, and custom resources."},
	{Id: "75", Title: "Docker Deep Dive", Author: "poulton", Genre: "devops", Year: 2023, Rating: 4.4,
		Synopsis: "Docker from basics to production. Covers images, containers, networking, volumes, Docker Compose, Swarm, security scanning, and CI/CD integration."},
	{Id: "76", Title: "Terraform: Up and Running", Author: "brikman", Genre: "devops", Year: 2022, Rating: 4.5,
		Synopsis: "Infrastructure as code with Terraform. Covers HCL syntax, state management, modules, testing, team workflows, and multi-cloud deployments."},
	{Id: "77", Title: "GitOps and Kubernetes", Author: "billimoria-hockin", Genre: "devops", Year: 2021, Rating: 4.2,
		Synopsis: "Continuous deployment with Git as single source of truth. Covers ArgoCD, Flux, progressive delivery, multi-cluster, and security considerations."},
	{Id: "78", Title: "Production Kubernetes", Author: "rosso-harris-saito-leroux", Genre: "devops", Year: 2021, Rating: 4.3,
		Synopsis: "Running Kubernetes in production. Covers networking, storage, security hardening, multi-tenancy, policy enforcement, and day-2 operations."},
	{Id: "79", Title: "Learning Helm", Author: "butcher-farina-matt", Genre: "devops", Year: 2021, Rating: 4.1,
		Synopsis: "Kubernetes package management with Helm. Covers charts, templates, hooks, library charts, OCI registries, and building a chart repository."},
	{Id: "80", Title: "Prometheus: Up and Running", Author: "brazil", Genre: "devops", Year: 2022, Rating: 4.3,
		Synopsis: "Monitoring with Prometheus. Covers metrics, PromQL, alerting, Grafana dashboards, service discovery, exporters, and long-term storage options."},

	// --- data ---
	{Id: "81", Title: "Fundamentals of Data Engineering", Author: "reis-housley", Genre: "data", Year: 2022, Rating: 4.5,
		Synopsis: "Modern data engineering lifecycle. Covers ingestion, transformation, storage, serving, orchestration, security, and DataOps across batch and streaming."},
	{Id: "82", Title: "Streaming Systems", Author: "akidau-chernyak-lax", Genre: "data", Year: 2018, Rating: 4.4,
		Synopsis: "Theory and practice of stream processing. Covers watermarks, windows, triggers, accumulation, exactly-once semantics, and the Dataflow model."},
	{Id: "83", Title: "Data Mesh", Author: "dehghani", Genre: "data", Year: 2022, Rating: 4.1,
		Synopsis: "Decentralized data architecture. Covers domain-oriented ownership, data as a product, self-serve platform, and federated computational governance."},
	{Id: "84", Title: "The Data Warehouse Toolkit", Author: "kimball-ross", Genre: "data", Year: 2013, Rating: 4.4,
		Synopsis: "Dimensional modeling guide. Covers star schemas, slowly changing dimensions, fact tables, bridge tables, and design patterns for enterprise data warehouses."},
	{Id: "85", Title: "Spark: The Definitive Guide", Author: "chambers-zaharia", Genre: "data", Year: 2018, Rating: 4.3,
		Synopsis: "Apache Spark from basics to advanced. Covers DataFrames, SQL, structured streaming, ML pipelines, graph analytics, and performance tuning."},
	{Id: "86", Title: "High Performance MySQL", Author: "schwartz-zaitsev-tkachenko", Genre: "data", Year: 2012, Rating: 4.4,
		Synopsis: "MySQL optimization deep dive. Covers schema design, indexing, query optimization, replication, high availability, backup, and performance monitoring."},
	{Id: "87", Title: "PostgreSQL 14 Internals", Author: "rogov", Genre: "data", Year: 2023, Rating: 4.5,
		Synopsis: "PostgreSQL architecture and internals. Covers MVCC, buffer cache, WAL, query planning, index types, vacuum, and the extension system."},
	{Id: "88", Title: "Redis in Action", Author: "carlson", Genre: "data", Year: 2013, Rating: 4.2,
		Synopsis: "Practical Redis patterns. Covers data structures, pub/sub, scripting with Lua, persistence, replication, clustering, and real-time analytics."},
	{Id: "89", Title: "Designing Event-Driven Systems", Author: "stopford", Genre: "data", Year: 2018, Rating: 4.2,
		Synopsis: "Event-driven architectures with Apache Kafka. Covers event sourcing, CQRS, event streaming as shared data layer, and microservice integration."},
	{Id: "90", Title: "Data-Intensive Text Processing with MapReduce", Author: "lin-dyer", Genre: "data", Year: 2010, Rating: 4.1,
		Synopsis: "Large-scale text analytics with MapReduce. Covers inverted indexing, graph algorithms, EM, and statistical NLP on distributed infrastructure."},

	// --- architecture ---
	{Id: "91", Title: "A Philosophy of Software Design", Author: "ousterhout", Genre: "architecture", Year: 2018, Rating: 4.5,
		Synopsis: "Principles for reducing complexity. Covers deep vs shallow modules, information hiding, strategic vs tactical programming, and comments as design."},
	{Id: "92", Title: "Software Architecture: The Hard Parts", Author: "ford-richards-sadalage-dehghani", Genre: "architecture", Year: 2021, Rating: 4.4,
		Synopsis: "Trade-off analysis for distributed architectures. Covers decomposition, data ownership, transactional sagas, contracts, and architecture decision records."},
	{Id: "93", Title: "Fundamentals of Software Architecture", Author: "ford-richards", Genre: "architecture", Year: 2020, Rating: 4.3,
		Synopsis: "Architect's reference covering styles (layered, microkernel, event-driven, microservices), characteristics, decisions, governance, and soft skills."},
	{Id: "94", Title: "Clean Architecture", Author: "martin-rc", Genre: "architecture", Year: 2017, Rating: 4.2,
		Synopsis: "Dependency rule and component principles. Covers screaming architecture, the humble object pattern, and boundaries between frameworks and business logic."},
	{Id: "95", Title: "Building Evolutionary Architectures", Author: "ford-parsons-kua", Genre: "architecture", Year: 2017, Rating: 4.1,
		Synopsis: "Architectures that support guided incremental change. Covers fitness functions, deployment pipelines, evolutionary data design, and organizational factors."},
	{Id: "96", Title: "Designing Distributed Systems", Author: "burns", Genre: "architecture", Year: 2018, Rating: 4.1,
		Synopsis: "Patterns for reliable distributed systems. Covers sidecars, ambassadors, adapters, sharded services, scatter/gather, and FaaS event-driven processing."},
	{Id: "97", Title: "Just Enough Software Architecture", Author: "fairbanks", Genre: "architecture", Year: 2010, Rating: 4.2,
		Synopsis: "Risk-driven architecture: model just enough to reduce risk. Covers views, quality attributes, architectural styles, and analysis techniques."},
	{Id: "98", Title: "Monolith to Microservices", Author: "newman", Genre: "architecture", Year: 2019, Rating: 4.3,
		Synopsis: "Practical migration strategies from monolith to microservices. Covers strangler fig, branch by abstraction, parallel run, and data decomposition."},
	{Id: "99", Title: "Technology Strategy Patterns", Author: "hewitt", Genre: "architecture", Year: 2018, Rating: 4.0,
		Synopsis: "Frameworks for technology decision-making. Covers landscape analysis, build vs buy, technical debt quantification, and architecture pitch decks."},
	{Id: "100", Title: "System Design Interview", Author: "xu", Genre: "architecture", Year: 2020, Rating: 4.4,
		Synopsis: "Step-by-step approach to system design problems. Covers URL shortener, chat system, news feed, notification service, and search autocomplete."},
}

// authors maps author IDs to display names.
var authors = map[string]string{
	"donovan-kernighan":              "Alan Donovan & Brian Kernighan",
	"hunt-thomas":                    "Andrew Hunt & David Thomas",
	"martin-rc":                      "Robert C. Martin",
	"fowler":                         "Martin Fowler",
	"brooks":                         "Frederick Brooks",
	"mcconnell":                      "Steve McConnell",
	"feathers":                       "Michael Feathers",
	"bentley":                        "Jon Bentley",
	"raymond":                        "Eric S. Raymond",
	"bloch":                          "Joshua Bloch",
	"crockford":                      "Douglas Crockford",
	"beazley-jones":                  "David Beazley & Brian K. Jones",
	"klabnik-nichols":                "Steve Klabnik & Carol Nichols",
	"evans":                          "Eric Evans",
	"beck":                           "Kent Beck",
	"freeman-robson":                 "Eric Freeman & Elisabeth Robson",
	"nygard":                         "Michael Nygard",
	"humble-farley":                  "Jez Humble & David Farley",
	"cox-buday":                      "Katherine Cox-Buday",
	"kleppmann":                      "Martin Kleppmann",
	"beyer-jones-petoff-murphy":      "Betsy Beyer, Chris Jones, Jennifer Petoff & Niall Murphy",
	"van-steen-tanenbaum":            "Maarten van Steen & Andrew Tanenbaum",
	"petrov":                         "Alex Petrov",
	"arpaci-dusseau":                 "Remzi Arpaci-Dusseau & Andrea Arpaci-Dusseau",
	"kurose-ross":                    "James Kurose & Keith Ross",
	"gregg":                          "Brendan Gregg",
	"newman":                         "Sam Newman",
	"narkhede-shapira-palino":        "Neha Narkhede, Gwen Shapira & Todd Palino",
	"vitillo":                        "Roberto Vitillo",
	"abbott-fisher":                  "Martin Abbott & Michael Fisher",
	"ejsmont":                        "Artur Ejsmont",
	"majors-fong-jones-miranda":      "Charity Majors, Liz Fong-Jones & George Miranda",
	"davis":                          "Cornelia Davis",
	"morris":                         "Kief Morris",
	"abelson-sussman":                "Harold Abelson & Gerald Sussman",
	"cormen-leiserson-rivest-stein":  "Thomas Cormen, Charles Leiserson, Ronald Rivest & Clifford Stein",
	"hofstadter":                     "Douglas Hofstadter",
	"knuth":                          "Donald Knuth",
	"pierce":                         "Benjamin Pierce",
	"aho-lam-sethi-ullman":           "Alfred Aho, Monica Lam, Ravi Sethi & Jeffrey Ullman",
	"milewski":                       "Bartosz Milewski",
	"okasaki":                        "Chris Okasaki",
	"graham-knuth-patashnik":         "Ronald Graham, Donald Knuth & Oren Patashnik",
	"friedman-felleisen":             "Daniel Friedman & Matthias Felleisen",
	"boolos-burgess-jeffrey":         "George Boolos, John Burgess & Richard Jeffrey",
	"skiena":                         "Steven Skiena",
	"mackay":                         "David MacKay",
	"goodfellow-bengio-courville":    "Ian Goodfellow, Yoshua Bengio & Aaron Courville",
	"bishop":                         "Christopher Bishop",
	"geron":                          "Aurélien Géron",
	"russell-norvig":                 "Stuart Russell & Peter Norvig",
	"jurafsky-martin":                "Daniel Jurafsky & James Martin",
	"sutton-barto":                   "Richard Sutton & Andrew Barto",
	"hastie-tibshirani-friedman":     "Trevor Hastie, Robert Tibshirani & Jerome Friedman",
	"murphy":                         "Kevin Murphy",
	"tunstall-von-werra-wolf":        "Lewis Tunstall, Leandro von Werra & Thomas Wolf",
	"huyen":                          "Chip Huyen",
	"burkov":                         "Andriy Burkov",
	"raschka":                        "Sebastian Raschka",
	"stuttard-pinto":                 "Dafydd Stuttard & Marcus Pinto",
	"ferguson-schneier-kohno":        "Niels Ferguson, Bruce Schneier & Tadayoshi Kohno",
	"shostack":                       "Adam Shostack",
	"aumasson":                       "Jean-Philippe Aumasson",
	"erickson":                       "Jon Erickson",
	"zalewski":                       "Michal Zalewski",
	"dotson":                         "Chris Dotson",
	"leblanc":                        "Jonathan LeBlanc",
	"ristic":                         "Ivan Ristić",
	"gilman-barth":                   "Evan Gilman & Doug Barth",
	"kim-behr-spafford":              "Gene Kim, Kevin Behr & George Spafford",
	"forsgren-humble-kim":            "Nicole Forsgren, Jez Humble & Gene Kim",
	"kim-humble-debois-willis":       "Gene Kim, Jez Humble, Patrick Debois & John Willis",
	"luksa":                          "Marko Lukša",
	"poulton":                        "Nigel Poulton",
	"brikman":                        "Yevgeniy Brikman",
	"billimoria-hockin":              "Billy Yuen & Tim Hockin",
	"rosso-harris-saito-leroux":      "Josh Rosso, Rich Lander, Craig Harris & Alexander Brand",
	"butcher-farina-matt":            "Matt Butcher, Matt Farina & Josh Dolitsky",
	"brazil":                         "Brian Brazil",
	"reis-housley":                   "Joe Reis & Matt Housley",
	"akidau-chernyak-lax":            "Tyler Akidau, Slava Chernyak & Reuven Lax",
	"dehghani":                       "Zhamak Dehghani",
	"kimball-ross":                   "Ralph Kimball & Margy Ross",
	"chambers-zaharia":               "Bill Chambers & Matei Zaharia",
	"schwartz-zaitsev-tkachenko":     "Baron Schwartz, Peter Zaitsev & Vadim Tkachenko",
	"rogov":                          "Egor Rogov",
	"carlson":                        "Josiah Carlson",
	"stopford":                       "Ben Stopford",
	"lin-dyer":                       "Jimmy Lin & Chris Dyer",
	"ousterhout":                     "John Ousterhout",
	"ford-richards-sadalage-dehghani": "Neal Ford, Mark Richards, Pramod Sadalage & Zhamak Dehghani",
	"ford-richards":                  "Neal Ford & Mark Richards",
	"ford-parsons-kua":               "Neal Ford, Rebecca Parsons & Patrick Kua",
	"burns":                          "Brendan Burns",
	"fairbanks":                      "George Fairbanks",
	"hewitt":                         "Eben Hewitt",
	"xu":                             "Alex Xu",
}
